CREATE TABLE CORE_CATEGORIA (
    ID NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50 CHAR) NOT NULL,
    IMAGEN VARCHAR2(1000 CHAR) NULL
);

CREATE TABLE CORE_MARCA (
    ID NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50 CHAR) NOT NULL
);

CREATE TABLE CORE_CLIENT (
    ID NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ADDRESS VARCHAR2(200 CHAR) NULL,
    BIRTHDATE DATE NOT NULL,
    USER_ID NUMBER(19,0) UNIQUE NOT NULL
);

CREATE TABLE CORE_USERPROFILE (
    ID NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE VARCHAR2(20 CHAR) DEFAULT 'cliente' NOT NULL,
    USER_ID NUMBER(19,0) UNIQUE NOT NULL
);

CREATE TABLE CORE_PRODUCTO (
    ID NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100 CHAR) NOT NULL,
    DESCRIPCION CLOB NOT NULL,
    PRECIO NUMBER(10,2) NOT NULL,
    STOCK NUMBER(10,0) NOT NULL,
    IMAGEN VARCHAR2(1000 CHAR) NULL,
    CATEGORIA_ID NUMBER(19,0) NOT NULL,
    MARCA_ID NUMBER(19,0) NOT NULL
);

CREATE TABLE CORE_VENTA (
    ID NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TOTAL NUMBER(10,2) NOT NULL,
    CLIENTE_ID NUMBER(19,0) NOT NULL
);

CREATE TABLE CORE_DETALLEVENTA (
    ID NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CANTIDAD NUMBER(10,0) NOT NULL,
    PRECIO_UNITARIO NUMBER(10,2) NOT NULL,
    PRODUCTO_ID NUMBER(19,0) NOT NULL,
    VENTA_ID NUMBER(19,0) NOT NULL
);

-- Claves foráneas
ALTER TABLE CORE_CLIENT
    ADD CONSTRAINT FK_CLIENT_USER FOREIGN KEY (USER_ID) REFERENCES AUTH_USER(ID);

ALTER TABLE CORE_USERPROFILE
    ADD CONSTRAINT FK_USERPROFILE_USER FOREIGN KEY (USER_ID) REFERENCES AUTH_USER(ID);

ALTER TABLE CORE_PRODUCTO
    ADD CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CORE_CATEGORIA(ID);

ALTER TABLE CORE_PRODUCTO
    ADD CONSTRAINT FK_PRODUCTO_MARCA FOREIGN KEY (MARCA_ID) REFERENCES CORE_MARCA(ID);

ALTER TABLE CORE_VENTA
    ADD CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CORE_CLIENT(ID);

ALTER TABLE CORE_DETALLEVENTA
    ADD CONSTRAINT FK_DETALLEVENTA_PRODUCTO FOREIGN KEY (PRODUCTO_ID) REFERENCES CORE_PRODUCTO(ID);

ALTER TABLE CORE_DETALLEVENTA
    ADD CONSTRAINT FK_DETALLEVENTA_VENTA FOREIGN KEY (VENTA_ID) REFERENCES CORE_VENTA(ID);