# Generated by Django 5.2.6 on 2025-09-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_alter_venta_cliente_delete_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nacimiento',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='lastname',
        ),
    ]
