# Generated by Django 5.2.6 on 2025-09-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_direccion_cliente_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
    ]
