# Generated by Django 5.2.6 on 2025-09-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categoria_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
